version: "3.5"
services:

  puppeteer:
    build: ./
    container_name: puppeteer
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /workspace
    stdin_open: true
    tty: true
